### ISSUE TITLE
Quad remesh appears to be broken

### ISSUE THREAD

**Issue by seongyeong2** [vork/PyNanoInstantMeshes#4]
Hello, first thank you for such a impressive code.

However, when performing quad remeshing using "pynim.remesh," I occasionally notice that the mesh geometry gets distorted. This issue does not occur with the same mesh when using InstantMeshes. 

Could you please look into this?

![image](https://github.com/user-attachments/assets/020161da-da5f-4a23-a930-0633287fcce5)

**Comment by vork** [comment]
I've just pushed an update. Try installing with:
`pip install -U git+https://github.com/vork/PyNanoInstantMeshes.git`
